[WIP] Refactor view
xtensor-stack/zarray pull request #28
Opened 2021-02-02 14:12 UTC by davidbrochart

I have compilation issues locally, let's see what the CI says.

2021-02-02 20:55 UTC, JohanMabille requested changes

2021-02-02 20:55 UTC, JohanMabille commented on include/zarray/zarray.hpp
> +        zarray_impl* make_view(xstrided_slice_vector& slices);
THis method should return a `zarray` object wrapping the `zarray_impl*` returned by the `make_view` method of `zarray_impl`

2021-02-02 20:55 UTC, JohanMabille commented on include/zarray/zarray_impl.hpp
> +        zarray_impl* p_impl = e.derived_cast().allocate_result();
`e.derived_cast()` is an xexpression that do not provide the `allocate_result` method. What you want to do here is build a `zexpression_wrapper` on the newly created strided_view:

```cpp
return build_zarray(std::move(e));
```

2021-02-02 20:55 UTC, JohanMabille commented on include/zarray/zarray_impl.hpp
> +        zarray_impl* p_impl = e.derived_cast().allocate_result();
same remark as previous

2021-02-02 20:55 UTC, JohanMabille commented on include/zarray/zarray_impl.hpp
> +        zarray_impl* p_impl = e.derived_cast().allocate_result();
Same remark here

2021-02-02 20:55 UTC, JohanMabille commented on include/zarray/zarray_impl.hpp
> +        zarray_impl* p_impl = e.derived_cast().allocate_result();
Same remark here

2021-02-03 18:34 UTC, davidbrochart commented
I couldn't use `detail::is_strided_view` because [it already exists](https://github.com/xtensor-stack/xtensor/blob/6846c156825356a62dc16193245936988793fe6e/include/xtensor/xview.hpp#L158-L164) (but it doesn't seem to be what we need here). So I named it `detail::is_a_strided_view` :smile:

2021-02-04 09:14 UTC, JohanMabille reviewed
I think the file `zview.hpp`  and the [zview_dispatcher](https://github.com/xtensor-stack/zarray/blob/master/include/zarray/zdispatcher.hpp#L51) can be removed.

2021-02-04 09:14 UTC, JohanMabille commented on include/zarray/zarray_impl.hpp
> +        struct is_a_strided_view : std::false_type
Nitpicking: could be `is_xstrided_view` to be consistent with `is_xarray` just below

2021-02-04 09:14 UTC, JohanMabille commented on include/zarray/zarray_impl.hpp
> +        template <class E, class S>
I think you could add the [additional template arguments](https://github.com/xtensor-stack/xtensor/blob/master/include/xtensor/xstrided_view.hpp#L125) of `xstrided_view` to be sure we can match all the cases.

2021-02-04 09:14 UTC, JohanMabille commented on include/zarray/zarray_impl.hpp
> +        auto e = xt::strided_view(m_cache, slices);
What about:

```cpp
auto e = xt::strided_view(get_array(), slices);
```

This way you're not exposed to the caching mechanism detail.

2021-02-04 09:39 UTC, JohanMabille approved these changes

2021-02-04 09:40 UTC, JohanMabille commented
Great! I'll merge when the CI is green.

2021-02-04 10:13 UTC, merged