initial version of zreducers
xtensor-stack/zarray pull request #56
Opened 2021-06-16 14:04 UTC by DerThorsten

2021-06-16 14:17 UTC, DerThorsten commented
Todos:
 * reducers which have a result type which differs from the input do not work yet.
  @JohanMabille  I might need your help here to register all the needed types.
 * add all the norms ..
 * re-enable the slow unit tests...

2021-06-17 11:05 UTC, DerThorsten commented
```
    template<class F>
    template <class T>
    inline std::size_t zreducer_functor<F>::index
    (
        const ztyped_array<T>& input_array,
        const zreducer_options& options
    )
    {
        std::size_t result;
        options.visit_reducer_options([&result, &input_array](auto&&... reduce_args)
        {
            using expr_type = decltype(F::run(input_array.get_array(), std::forward<decltype(reduce_args)>(reduce_args)...));
            using expr_value_type = typename std::decay_t<expr_type>::value_type;
            result = ztyped_array<expr_value_type>::get_class_static_index();
        });
        return result;
    }
```
gcc 4 fails to capture `input_array`.   I disable gcc 4 in the ci (for the moment,..)

2021-06-17 17:27 UTC, JohanMabille requested changes
The implementation is really neat, I only have nitpicking remarks and a concern regarding the usage of the `shared_ptr` in zreducer_options. I finally think having the init functions in a dedicated header is more intuitive for the user.

Also do not forget to add the ne header to the CmakeLists.txt, otherwise they won't be installed when running `cmake install`.

2021-06-17 17:27 UTC, JohanMabille commented on include/zarray/zarray_impl_register.hpp
> +#ifndef XTENSOR_ZARRY_IMPL_REGISTER_HPP
Typo: should be `XTENSOR_ZARRAY_IMPL_REGISTER_HPP`

2021-06-17 17:27 UTC, JohanMabille commented on include/zarray/zinit.hpp
> +
nitpicking: no need for extra new lines

2021-06-17 17:27 UTC, JohanMabille commented on include/zarray/zinit.hpp
> +     *************************************/
Nitpicking: this comment can be removed.

2021-06-17 17:27 UTC, JohanMabille commented on include/zarray/zmath.hpp
> +
Nitpicking:; no need for extra new lines

2021-06-17 17:27 UTC, JohanMabille commented on include/zarray/zreducer.hpp
> +    void zreducer<F,CT>::init_result_shape(){
Nitpicking: opening curly brace goes on a new line

2021-06-17 17:27 UTC, JohanMabille commented on include/zarray/zreducer.hpp
> +        else{
same here

2021-06-17 17:27 UTC, JohanMabille commented on include/zarray/zreducer.hpp
> +
No need for extra new lines here.

2021-06-17 17:27 UTC, JohanMabille commented on include/zarray/zreducer_options.hpp
> +    class zreducer_options{
Nitpicking; opening curly brace goe son a new line

2021-06-17 17:27 UTC, JohanMabille commented on include/zarray/zreducer_options.hpp
> +        using make_scalar_wrapper_t = zscalar_wrapper<xscalar<T>>;
Naming; usually, `make_xxx` are used for builder functions, I think `scalar_wrapper_type` would be fine here.

2021-06-17 17:27 UTC, JohanMabille commented on include/zarray/zreducer_options.hpp
> +        void visit_reducer_options(const bool force_lazy, F && f)const;
No need to add const for arguments passed by copy.

2021-06-17 17:27 UTC, JohanMabille commented on test/test_zfunction.cpp
> +    // }
Why keeping commented code here?

2021-06-17 17:27 UTC, JohanMabille commented on include/zarray/zreducer_options.hpp
> +        std::shared_ptr<zarray_impl> m_inital_value;
typo: `m_initial_value`.

I still have a concern with the usage of `shared_ptr` here, it should not be required. What is the cyclic dependency if you include `zarray_zarray.hpp` here?

2021-06-18 11:37 UTC, JohanMabille approved these changes

2021-06-18 11:56 UTC, merged